pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
       stage('Hello World Container') {
            agent {
                docker {
                    image 'ubuntu:latest' // Use a base image like Ubuntu or Alpine
                }
            }
            steps {
                sh 'echo "Hello from inside the container!"'
                sh 'ls -la /' // Example: list directory contents inside the container
            }
        }
  }
}
